username: XXXXXX@gmail.com
password: XXXXX

positions:
  - java


locations:
  - europe
  - # A second location you want to search in

    #uploads:
    #  Resume: /Users/vikasjaiswal/Vikas_Jaiswal_9_Years_Exp -pdf
    #  Cover Letter: # PATH TO cover letter
    #  Photo: # PATH TO photo
    ## Note file_key:file_paths contained inside the uploads section should be writted without a dash ('-')
    #
    #output_filename:
    #  - # PATH TO OUTPUT FILE (default output.csv)
    #
  #blacklist:
#  - # Company names you want to ignore